baseURL = "/"
defaultContentLanguage = "it"
defaultContentLanguageInSubdir = true
title = "Spada Reale"

disableKinds = ["taxonomy", "term"]

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]

[languages]
  [languages.it]
    languageName = "Italiano"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
  [languages.fr]
    languageName = "Fran√ßais"
    weight = 3