baseURL = "/"
defaultContentLanguage = "it"
defaultContentLanguageInSubdir = true
title = "Spada Reale"

disableKinds = ["taxonomy", "term"]

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]

[languages]

  [languages.it]
    languageName = "Italiano"
    languageCode = "it-IT"
    weight = 1
    contentDir = "content/it"

  [languages.en]
    languageName = "English"
    languageCode = "en-GB"
    weight = 2
    contentDir = "content/en"

  [languages.fr]
    languageName = "Fran√ßais"
    languageCode = "fr-FR"
    weight = 3
    contentDir = "content/fr"